# Generated by Django 2.2.24 on 2021-12-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0002_auto_20211214_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Once You Are In Hell, Only The Devil Can Help You Out.', max_length=500),
        ),
    ]
