# Generated by Django 2.2.24 on 2021-12-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0003_auto_20211214_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hello, I want to play a game', max_length=500),
        ),
    ]
